language: node_js
node_js: 
  - "12.18.1"

branches:
  only:
    - hexo2.0

# Start: Build Lifecycle
before_install: # 配置环境 安装 hexo 和 pandoc
  - npm install -g hexo-cli
  - npm install --save bulma-stylus@0.8.0 hexo-pagination@^2.0.0

install:
  - npm install

script:
  - hexo clean

after_success:
  - hexo generate
  - hexo deploy
