language: node_js
node_js: 
  - "10.15.1"

install:
  - npm install
  - npm install -g hexo-cli
  - npm install hexo-deployer-git

script:
  - hexo clean
  - hexo deploy

branches:
  only:
    - hexo2.0
