language: node_js
node_js: 
  - "12.18.1"

branches:
  only:
    - hexo2.0

# Start: Build Lifecycle
before_install: # 配置环境 安装 hexo 和 pandoc
  - npm install -g hexo-cli
  - npm install --save bulma-stylus@0.8.0 hexo-pagination@^2.0.0

install:
  # - npm install

script:
  - hexo clean
  - rm -rf .deploy_git
  - hexo generate

deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true
  github-token: $GH_TOKEN # $GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  local-dir: public # 静态站点文件所在目录
  keep-history: true # 是否保持target-branch分支的提交记录
  target-branch: master # 发布分支
  on:
    branch: hexo2.0 # 源码分支